---

  #
  # compile rtl8812au wifi driver for raspbian
  #
  # https://github.com/notro/rpi-source/wiki
  # https://github.com/gnab/rtl8812au
  #
  - name: Install necessary packages
    become: yes
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    with_items:
      - git
      - bc

  - name: Download rpi-source
    become: yes
    get_url:
      url: "https://raw.githubusercontent.com/notro/rpi-source/master/rpi-source"
      dest: "/usr/bin/rpi-source"
      owner: root
      group: root
      mode: 0755

  # TODO: make idempotent
  - name: Run rpi-source to download current raspbian kernel source
    become: no
    command: rpi-source
    register: rpi_result
    failed_when: "rpi_result.rc > 1"

  - name: Clone git repo for rtl8812au wifi driver
    become: no
    git:
      clone: yes
      update: no
      repo: "https://github.com/gnab/rtl8812au"
      dest: "/tmp/rtl8812au"

  - name: Disable CONFIG_PLATFORM_I386_PC in Makefile
    become: no
    lineinfile:
      dest: "/tmp/rtl8812au/Makefile"
      regexp: "^CONFIG_PLATFORM_I386_PC"
      line: "CONFIG_PLATFORM_I386_PC = n"
      state: present
      backrefs: yes
      backup: yes

  - name: Enable CONFIG_PLATFORM_ARM_RPI in Makefile
    become: no
    lineinfile:
      dest: "/tmp/rtl8812au/Makefile"
      regexp: "^CONFIG_PLATFORM_ARM_RPI"
      line: "CONFIG_PLATFORM_ARM_RPI = y"
      state: present
      backrefs: yes
      backup: yes

  - name: Make the rtl8812au wifi driver
    become: no
    make:
      chdir: "/tmp/rtl8812au"

  - name: Copy compiled 8812au.ko module to kernel modules
    become: yes
    copy:
      src: "/tmp/rtl8812au/8812au.ko"
      dest: "/lib/modules/{{ ansible_kernel }}/kernel/drivers/net/wireless"
      remote_src: yes

  - name: Run depmod
    become: yes
    command: depmod -a

  - name: Modprobe 8812au.ko
    become: yes
    modprobe:
      name: 8812au
